export type TTSVoice = {
  id: string;
  label: string;
  locale: string;
};

export const TTS_VOICES_SHORT: TTSVoice[] = [
  { id: "ru-RU-SvetlanaNeural", label: "Светлана", locale: "ru-RU" },
  { id: "ru-RU-DmitryNeural", label: "Дмитрий", locale: "ru-RU" },
];

export const TTS_VOICES: TTSVoice[] = [
  { id: "ru-RU-SvetlanaNeural", label: "Светлана", locale: "ru-RU" },
  { id: "ru-RU-DmitryNeural", label: "Дмитрий", locale: "ru-RU" },
  { id: "bg-BG-KalinaNeural", label: "Калина", locale: "bg-BG" },
  { id: "bg-BG-BorislavNeural", label: "Борислав", locale: "bg-BG" },
  { id: "bn-BD-NabanitaNeural", label: "নবনীতা", locale: "bn-BD" },
  { id: "bn-BD-PradeepNeural", label: "প্রদ্বীপ", locale: "bn-BD" },
  { id: "bs-BA-VesnaNeural", label: "Vesna", locale: "bs-BA" },
  { id: "bs-BA-GoranNeural", label: "Goran", locale: "bs-BA" },
  { id: "ca-ES-JoanaNeural", label: "Joana", locale: "ca-ES" },
  { id: "ca-ES-EnricNeural", label: "Enric", locale: "ca-ES" },
  { id: "cs-CZ-VlastaNeural", label: "Vlasta", locale: "cs-CZ" },
  { id: "cs-CZ-AntoninNeural", label: "Antonín", locale: "cs-CZ" },
  { id: "cy-GB-NiaNeural", label: "Nia", locale: "cy-GB" },
  { id: "cy-GB-AledNeural", label: "Aled", locale: "cy-GB" },
  { id: "da-DK-ChristelNeural", label: "Christel", locale: "da-DK" },
  { id: "da-DK-JeppeNeural", label: "Jeppe", locale: "da-DK" },
  { id: "de-AT-IngridNeural", label: "Ingrid", locale: "de-AT" },
  { id: "de-AT-JonasNeural", label: "Jonas", locale: "de-AT" },
  { id: "de-CH-LeniNeural", label: "Leni", locale: "de-CH" },
  { id: "de-CH-JanNeural", label: "Jan", locale: "de-CH" },
  {
    id: "de-DE-SeraphinaMultilingualNeural",
    label: "Seraphina Mehrsprachig",
    locale: "de-DE",
  },
  {
    id: "de-DE-FlorianMultilingualNeural",
    label: "Florian Mehrsprachig",
    locale: "de-DE",
  },
  { id: "de-DE-KatjaNeural", label: "Katja", locale: "de-DE" },
  { id: "de-DE-ConradNeural", label: "Conrad", locale: "de-DE" },
  { id: "de-DE-AmalaNeural", label: "Amala", locale: "de-DE" },
  { id: "de-DE-KillianNeural", label: "Killian", locale: "de-DE" },
  {
    id: "en-AU-WilliamMultilingualNeural",
    label: "William Multilingual",
    locale: "en-AU",
  },
  { id: "en-AU-NatashaNeural", label: "Natasha", locale: "en-AU" },
  { id: "en-CA-ClaraNeural", label: "Clara", locale: "en-CA" },
  { id: "en-CA-LiamNeural", label: "Liam", locale: "en-CA" },
  { id: "en-GB-SoniaNeural", label: "Sonia", locale: "en-GB" },
  { id: "en-GB-RyanNeural", label: "Ryan", locale: "en-GB" },
  { id: "en-GB-LibbyNeural", label: "Libby", locale: "en-GB" },
  { id: "en-GB-MaisieNeural", label: "Maisie", locale: "en-GB" },
  { id: "en-GB-ThomasNeural", label: "Thomas", locale: "en-GB" },
  { id: "en-HK-YanNeural", label: "Yan", locale: "en-HK" },
  { id: "en-HK-SamNeural", label: "Sam", locale: "en-HK" },
  { id: "en-IE-EmilyNeural", label: "Emily", locale: "en-IE" },
  { id: "en-IE-ConnorNeural", label: "Connor", locale: "en-IE" },
  { id: "en-IN-NeerjaNeural", label: "Neerja", locale: "en-IN" },
  { id: "en-IN-PrabhatNeural", label: "Prabhat", locale: "en-IN" },
  { id: "en-KE-AsiliaNeural", label: "Asilia", locale: "en-KE" },
  { id: "en-KE-ChilembaNeural", label: "Chilemba", locale: "en-KE" },
  { id: "en-NG-EzinneNeural", label: "Ezinne", locale: "en-NG" },
  { id: "en-NG-AbeoNeural", label: "Abeo", locale: "en-NG" },
  { id: "en-NZ-MollyNeural", label: "Molly", locale: "en-NZ" },
  { id: "en-NZ-MitchellNeural", label: "Mitchell", locale: "en-NZ" },
  { id: "en-PH-RosaNeural", label: "Rosa", locale: "en-PH" },
  { id: "en-PH-JamesNeural", label: "James", locale: "en-PH" },
  { id: "en-SG-LunaNeural", label: "Luna", locale: "en-SG" },
  { id: "en-SG-WayneNeural", label: "Wayne", locale: "en-SG" },
  { id: "en-TZ-ImaniNeural", label: "Imani", locale: "en-TZ" },
  { id: "en-TZ-ElimuNeural", label: "Elimu", locale: "en-TZ" },
  {
    id: "en-US-AvaMultilingualNeural",
    label: "Ava Multilingual",
    locale: "en-US",
  },
  {
    id: "en-US-AndrewMultilingualNeural",
    label: "Andrew Multilingual",
    locale: "en-US",
  },
  {
    id: "en-US-EmmaMultilingualNeural",
    label: "Emma Multilingual",
    locale: "en-US",
  },
  {
    id: "en-US-BrianMultilingualNeural",
    label: "Brian Multilingual",
    locale: "en-US",
  },
  { id: "en-US-AvaNeural", label: "Ava", locale: "en-US" },
  { id: "en-US-AndrewNeural", label: "Andrew", locale: "en-US" },
  { id: "en-US-EmmaNeural", label: "Emma", locale: "en-US" },
  { id: "en-US-BrianNeural", label: "Brian", locale: "en-US" },
  { id: "en-US-JennyNeural", label: "Jenny", locale: "en-US" },
  { id: "en-US-GuyNeural", label: "Guy", locale: "en-US" },
  { id: "en-US-AriaNeural", label: "Aria", locale: "en-US" },
  { id: "en-US-AnaNeural", label: "Ana", locale: "en-US" },
  { id: "en-US-ChristopherNeural", label: "Christopher", locale: "en-US" },
  { id: "en-US-EricNeural", label: "Eric", locale: "en-US" },
  { id: "en-US-MichelleNeural", label: "Michelle", locale: "en-US" },
  { id: "en-US-RogerNeural", label: "Roger", locale: "en-US" },
  { id: "en-US-SteffanNeural", label: "Steffan", locale: "en-US" },
  { id: "en-ZA-LeahNeural", label: "Leah", locale: "en-ZA" },
  { id: "en-ZA-LukeNeural", label: "Luke", locale: "en-ZA" },
  { id: "es-AR-ElenaNeural", label: "Elena", locale: "es-AR" },
  { id: "es-AR-TomasNeural", label: "Tomas", locale: "es-AR" },
  { id: "es-BO-SofiaNeural", label: "Sofia", locale: "es-BO" },
  { id: "es-BO-MarceloNeural", label: "Marcelo", locale: "es-BO" },
  { id: "es-CL-CatalinaNeural", label: "Catalina", locale: "es-CL" },
  { id: "es-CL-LorenzoNeural", label: "Lorenzo", locale: "es-CL" },
  { id: "es-CO-SalomeNeural", label: "Salome", locale: "es-CO" },
  { id: "es-CO-GonzaloNeural", label: "Gonzalo", locale: "es-CO" },
  { id: "es-CR-MariaNeural", label: "María", locale: "es-CR" },
  { id: "es-CR-JuanNeural", label: "Juan", locale: "es-CR" },
  { id: "es-CU-BelkysNeural", label: "Belkys", locale: "es-CU" },
  { id: "es-CU-ManuelNeural", label: "Manuel", locale: "es-CU" },
  { id: "es-DO-RamonaNeural", label: "Ramona", locale: "es-DO" },
  { id: "es-DO-EmilioNeural", label: "Emilio", locale: "es-DO" },
  { id: "es-EC-AndreaNeural", label: "Andrea", locale: "es-EC" },
  { id: "es-EC-LuisNeural", label: "Luis", locale: "es-EC" },
  { id: "es-ES-ElviraNeural", label: "Elvira", locale: "es-ES" },
  { id: "es-ES-AlvaroNeural", label: "Álvaro", locale: "es-ES" },
  { id: "es-ES-XimenaNeural", label: "Ximena", locale: "es-ES" },
  { id: "es-GQ-TeresaNeural", label: "Teresa", locale: "es-GQ" },
  { id: "es-GQ-JavierNeural", label: "Javier", locale: "es-GQ" },
  { id: "es-GT-MartaNeural", label: "Marta", locale: "es-GT" },
  { id: "es-GT-AndresNeural", label: "Andrés", locale: "es-GT" },
  { id: "es-HN-KarlaNeural", label: "Karla", locale: "es-HN" },
  { id: "es-HN-CarlosNeural", label: "Carlos", locale: "es-HN" },
  { id: "es-MX-DaliaNeural", label: "Dalia", locale: "es-MX" },
  { id: "es-MX-JorgeNeural", label: "Jorge", locale: "es-MX" },
  { id: "es-NI-YolandaNeural", label: "Yolanda", locale: "es-NI" },
  { id: "es-NI-FedericoNeural", label: "Federico", locale: "es-NI" },
  { id: "es-PA-MargaritaNeural", label: "Margarita", locale: "es-PA" },
  { id: "es-PA-RobertoNeural", label: "Roberto", locale: "es-PA" },
  { id: "es-PE-CamilaNeural", label: "Camila", locale: "es-PE" },
  { id: "es-PE-AlexNeural", label: "Alex", locale: "es-PE" },
  { id: "es-PR-KarinaNeural", label: "Karina", locale: "es-PR" },
  { id: "es-PR-VictorNeural", label: "Víctor", locale: "es-PR" },
  { id: "es-PY-TaniaNeural", label: "Tania", locale: "es-PY" },
  { id: "es-PY-MarioNeural", label: "Mario", locale: "es-PY" },
  { id: "es-SV-LorenaNeural", label: "Lorena", locale: "es-SV" },
  { id: "es-SV-RodrigoNeural", label: "Rodrigo", locale: "es-SV" },
  { id: "es-US-PalomaNeural", label: "Paloma", locale: "es-US" },
  { id: "es-US-AlonsoNeural", label: "Alonso", locale: "es-US" },
  { id: "es-UY-ValentinaNeural", label: "Valentina", locale: "es-UY" },
  { id: "es-UY-MateoNeural", label: "Mateo", locale: "es-UY" },
  { id: "es-VE-PaolaNeural", label: "Paola", locale: "es-VE" },
  { id: "es-VE-SebastianNeural", label: "Sebastián", locale: "es-VE" },
  { id: "et-EE-AnuNeural", label: "Anu", locale: "et-EE" },
  { id: "et-EE-KertNeural", label: "Kert", locale: "et-EE" },
  { id: "fr-BE-CharlineNeural", label: "Charline", locale: "fr-BE" },
  { id: "fr-BE-GerardNeural", label: "Gerard", locale: "fr-BE" },
  { id: "fr-CA-SylvieNeural", label: "Sylvie", locale: "fr-CA" },
  { id: "fr-CA-JeanNeural", label: "Jean", locale: "fr-CA" },
  { id: "fr-CA-AntoineNeural", label: "Antoine", locale: "fr-CA" },
  { id: "fr-CA-ThierryNeural", label: "Thierry", locale: "fr-CA" },
  { id: "fr-CH-ArianeNeural", label: "Ariane", locale: "fr-CH" },
  { id: "fr-CH-FabriceNeural", label: "Fabrice", locale: "fr-CH" },
  { id: "fr-FR-DeniseNeural", label: "Denise", locale: "fr-FR" },
  { id: "fr-FR-HenriNeural", label: "Henri", locale: "fr-FR" },
  {
    id: "fr-FR-VivienneMultilingualNeural",
    label: "Vivienne Multilingue",
    locale: "fr-FR",
  },
  {
    id: "fr-FR-RemyMultilingualNeural",
    label: "Rémy Multilingue",
    locale: "fr-FR",
  },
  { id: "fr-FR-EloiseNeural", label: "Eloise", locale: "fr-FR" },
  { id: "ga-IE-OrlaNeural", label: "Orla", locale: "ga-IE" },
  { id: "ga-IE-ColmNeural", label: "Colm", locale: "ga-IE" },
  { id: "gl-ES-SabelaNeural", label: "Sabela", locale: "gl-ES" },
  { id: "gl-ES-RoiNeural", label: "Roi", locale: "gl-ES" },
  { id: "it-IT-ElsaNeural", label: "Elsa", locale: "it-IT" },
  { id: "it-IT-IsabellaNeural", label: "Isabella", locale: "it-IT" },
  { id: "it-IT-DiegoNeural", label: "Diego", locale: "it-IT" },
  {
    id: "it-IT-GiuseppeMultilingualNeural",
    label: "Giuseppe Multilingual",
    locale: "it-IT",
  },
  { id: "ja-JP-NanamiNeural", label: "七海", locale: "ja-JP" },
  { id: "ja-JP-KeitaNeural", label: "圭太", locale: "ja-JP" },
  { id: "jv-ID-SitiNeural", label: "Siti", locale: "jv-ID" },
  { id: "jv-ID-DimasNeural", label: "Dimas", locale: "jv-ID" },
  { id: "ka-GE-EkaNeural", label: "ეკა", locale: "ka-GE" },
  { id: "ka-GE-GiorgiNeural", label: "გიორგი", locale: "ka-GE" },
  { id: "kk-KZ-AigulNeural", label: "Айгүл", locale: "kk-KZ" },
  { id: "kk-KZ-DauletNeural", label: "Дәулет", locale: "kk-KZ" },
  { id: "ko-KR-SunHiNeural", label: "선히", locale: "ko-KR" },
  { id: "ko-KR-InJoonNeural", label: "인준", locale: "ko-KR" },
  {
    id: "ko-KR-HyunsuMultilingualNeural",
    label: "Hyunsu Multilingual",
    locale: "ko-KR",
  },
  { id: "pl-PL-MarekNeural", label: "Marek", locale: "pl-PL" },
  { id: "pl-PL-ZofiaNeural", label: "Zofia", locale: "pl-PL" },
  { id: "ro-RO-AlinaNeural", label: "Alina", locale: "ro-RO" },
  { id: "ro-RO-EmilNeural", label: "Emil", locale: "ro-RO" },
  { id: "sr-RS-SophieNeural", label: "Софија", locale: "sr-RS" },
  { id: "sr-RS-NicholasNeural", label: "Никола", locale: "sr-RS" },
  { id: "su-ID-TutiNeural", label: "Tuti", locale: "su-ID" },
  { id: "su-ID-JajangNeural", label: "Jajang", locale: "su-ID" },
  { id: "sv-SE-SofieNeural", label: "Sofie", locale: "sv-SE" },
  { id: "sv-SE-MattiasNeural", label: "Mattias", locale: "sv-SE" },
  { id: "sw-KE-ZuriNeural", label: "Zuri", locale: "sw-KE" },
  { id: "sw-KE-RafikiNeural", label: "Rafiki", locale: "sw-KE" },
  { id: "sw-TZ-RehemaNeural", label: "Rehema", locale: "sw-TZ" },
  { id: "sw-TZ-DaudiNeural", label: "Daudi", locale: "sw-TZ" },
  { id: "uk-UA-PolinaNeural", label: "Поліна", locale: "uk-UA" },
  { id: "uk-UA-OstapNeural", label: "Остап", locale: "uk-UA" },
];

export const TTS_DEFAULTS = {
  voice: "ru-RU-SvetlanaNeural",
  pitch: 0, // Hz
  rate: 25, // %
  volume: 0, // %
};
